global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.ModelBinding;
global using ErrorOr;
global using Domain.Services;
global using Domain.Data;
global using Domain.Interfaces;
global using WebAPI.Contracts.Cat;
global using Database;
global using Microsoft.EntityFrameworkCore;